name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  make-release:
    name: Create release
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts 
        uses: actions/download-artifact@v4
        with:
          name: jars

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: threadtweak*.jar
